name: lstm
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pandas
  - scikit-learn
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - ipykernel
  - pip
  - pip:
    - matplotlib
    - tqdm